/**
 * Seed data - structured ingredients (name/quantity/unit) power the shopping
 * list aggregator and nutrition estimator, while `raw` keeps the original
 * display string for the UI.
 */

const recipes = [
  {
    title: 'Butter Chicken',
    cuisine: 'Indian',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80',
    timeMinutes: 50,
    difficulty: 'Medium',
    servings: 4,
    description:
      'Tender chicken simmered in a velvety tomato-cream sauce spiced with garam masala, cumin and fenugreek. The definitive Indian comfort classic.',
    keywords: ['chicken', 'tomato', 'cream', 'butter', 'masala', 'curry'],
    dietTags: ['gluten-free'],
    ingredients: [
      { name: 'chicken', quantity: 700, unit: 'g', raw: '700g boneless chicken, cubed' },
      { name: 'yogurt', quantity: 200, unit: 'g', raw: '200g Greek yogurt' },
      { name: 'garam masala', quantity: 2, unit: 'tsp', raw: '2 tsp garam masala' },
      { name: 'cumin', quantity: 1, unit: 'tsp', raw: '1 tsp cumin' },
      { name: 'turmeric', quantity: 1, unit: 'tsp', raw: '1 tsp turmeric' },
      { name: 'chili powder', quantity: 1, unit: 'tsp', raw: '1 tsp chili powder' },
      { name: 'tomato', quantity: 400, unit: 'g', raw: '400g crushed tomatoes' },
      { name: 'cream', quantity: 150, unit: 'ml', raw: '150ml heavy cream' },
      { name: 'butter', quantity: 2, unit: 'tbsp', raw: '2 tbsp butter' },
      { name: 'garlic', quantity: 2, unit: 'whole', raw: '2 garlic cloves' },
    ],
    steps: [
      'Marinate chicken in yogurt and half the spices for at least 1 hour.',
      'Grill or pan-sear chicken until slightly charred; set aside.',
      'In the same pan, melt butter and sauté garlic + ginger paste.',
      'Add crushed tomatoes and remaining spices; simmer 15 min.',
      'Blend sauce smooth. Return to pan, add cream and chicken.',
      'Simmer 10 min. Finish with kasuri methi and serve with naan.',
    ],
  },
  {
    title: 'Masala Dosa',
    cuisine: 'Indian',
    image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=600&q=80',
    timeMinutes: 40,
    difficulty: 'Medium',
    servings: 4,
    description:
      'A crispy fermented rice-and-lentil crepe filled with spiced potato masala, served with coconut chutney and tangy sambar.',
    keywords: ['rice', 'lentil', 'potato', 'dosa', 'south indian', 'vegan'],
    dietTags: ['vegan', 'vegetarian'],
    ingredients: [
      { name: 'rice', quantity: 2, unit: 'cup', raw: '2 cups rice' },
      { name: 'lentil', quantity: 0.5, unit: 'cup', raw: '½ cup urad dal, soaked overnight' },
      { name: 'potato', quantity: 3, unit: 'whole', raw: '3 large potatoes, boiled & mashed' },
      { name: 'onion', quantity: 2, unit: 'whole', raw: '2 onions' },
      { name: 'coconut', quantity: 0.5, unit: 'cup', raw: 'coconut chutney to serve' },
    ],
    steps: [
      'Grind soaked rice and dal into a smooth batter; ferment overnight.',
      'Heat a non-stick tawa, spread batter in thin circles.',
      'Cook until golden and crisp on the edges.',
      'For the filling: sauté mustard seeds, onions, chillies.',
      'Add mashed potato, turmeric and salt; mix well.',
      'Place potato filling on dosa, fold and serve with chutney.',
    ],
  },
  {
    title: 'Pasta Carbonara',
    cuisine: 'Italian',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=600&q=80',
    timeMinutes: 25,
    difficulty: 'Easy',
    servings: 2,
    description:
      'The Roman original — silky eggs and Pecorino Romano emulsified with guanciale and plenty of black pepper. No cream, ever.',
    keywords: ['pasta', 'egg', 'cheese', 'pork', 'guanciale', 'bacon'],
    dietTags: [],
    ingredients: [
      { name: 'pasta', quantity: 200, unit: 'g', raw: '200g spaghetti or rigatoni' },
      { name: 'pork', quantity: 150, unit: 'g', raw: '150g guanciale or pancetta, cubed' },
      { name: 'egg', quantity: 4, unit: 'whole', raw: '3 egg yolks + 1 whole egg' },
      { name: 'cheese', quantity: 60, unit: 'g', raw: '60g Pecorino Romano, grated' },
      { name: 'cheese', quantity: 30, unit: 'g', raw: '30g Parmesan, grated' },
    ],
    steps: [
      'Cook pasta in well-salted boiling water al dente. Reserve 1 cup pasta water.',
      'Render guanciale in a cold pan until crispy; remove from heat.',
      'Whisk egg yolks, whole egg and grated cheese together.',
      'Drain pasta, add to the pan with guanciale off heat.',
      'Pour egg mixture over, toss vigorously, adding pasta water to create a glossy sauce.',
      'Serve immediately with extra cheese and black pepper.',
    ],
  },
  {
    title: 'Margherita Pizza',
    cuisine: 'Italian',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80',
    timeMinutes: 45,
    difficulty: 'Easy',
    servings: 2,
    description:
      'The timeless Neapolitan classic — thin, airy crust, San Marzano tomato sauce, fresh mozzarella and fragrant basil.',
    keywords: ['pizza', 'tomato', 'mozzarella', 'basil', 'dough', 'cheese'],
    dietTags: ['vegetarian'],
    ingredients: [
      { name: 'flour', quantity: 300, unit: 'g', raw: 'pizza dough (300g flour equivalent)' },
      { name: 'tomato', quantity: 1, unit: 'cup', raw: '1 cup San Marzano tomatoes, crushed' },
      { name: 'mozzarella', quantity: 200, unit: 'g', raw: '200g fresh mozzarella di bufala' },
      { name: 'oil', quantity: 2, unit: 'tbsp', raw: '2 tbsp extra-virgin olive oil' },
    ],
    steps: [
      'Preheat oven to 250 °C with a pizza stone or baking sheet inside.',
      'Roll dough thin on a floured surface to ~12 inches.',
      'Spread crushed tomatoes, leaving a 2 cm border.',
      'Tear mozzarella over the sauce.',
      'Bake 10–12 min until crust is golden and cheese is bubbling.',
      'Top with fresh basil and a drizzle of olive oil. Serve immediately.',
    ],
  },
  {
    title: 'Egg Fried Rice',
    cuisine: 'Chinese',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80',
    timeMinutes: 20,
    difficulty: 'Easy',
    servings: 2,
    description:
      'Restaurant-style wok-tossed fried rice with fluffy scrambled eggs, spring onions, soy sauce and sesame oil. The perfect weeknight staple.',
    keywords: ['rice', 'egg', 'soy', 'vegetable', 'wok', 'quick', 'sesame'],
    dietTags: ['vegetarian'],
    ingredients: [
      { name: 'rice', quantity: 2, unit: 'cup', raw: '2 cups day-old cooked jasmine rice' },
      { name: 'egg', quantity: 3, unit: 'whole', raw: '3 eggs, lightly beaten' },
      { name: 'soy', quantity: 2, unit: 'tbsp', raw: '2 tbsp soy sauce' },
      { name: 'sesame', quantity: 1, unit: 'tsp', raw: '1 tsp sesame oil' },
      { name: 'oil', quantity: 2, unit: 'tbsp', raw: '2 tbsp vegetable oil' },
    ],
    steps: [
      'Heat wok or large skillet until smoking hot. Add oil.',
      'Scramble eggs in the wok, breaking into small pieces. Set aside.',
      'Add garlic, stir-fry 30 seconds. Add cold rice, press flat.',
      'Toss rice over high heat for 2–3 min until separated and slightly toasty.',
      'Return eggs, add soy sauce and sesame oil. Toss everything together.',
      'Garnish with spring onions. Season with white pepper and serve hot.',
    ],
  },
  {
    title: 'Steamed Dumplings (Jiaozi)',
    cuisine: 'Chinese',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&q=80',
    timeMinutes: 60,
    difficulty: 'Medium',
    servings: 4,
    description:
      'Delicate handmade dumplings filled with pork, ginger, cabbage and sesame oil — steamed to pillowy perfection and served with chilli-soy dipping sauce.',
    keywords: ['pork', 'cabbage', 'ginger', 'dumpling', 'dim sum', 'steamed'],
    dietTags: [],
    ingredients: [
      { name: 'flour', quantity: 2, unit: 'cup', raw: '2 cups all-purpose flour' },
      { name: 'pork', quantity: 300, unit: 'g', raw: '300g ground pork' },
      { name: 'cabbage', quantity: 1, unit: 'cup', raw: '1 cup napa cabbage, salted & squeezed dry' },
      { name: 'soy', quantity: 2, unit: 'tbsp', raw: '2 tbsp soy sauce' },
      { name: 'sesame', quantity: 1, unit: 'tsp', raw: '1 tsp sesame oil' },
    ],
    steps: [
      'Mix flour and hot water; knead until smooth. Rest 30 min covered.',
      'Combine all filling ingredients; mix until sticky.',
      'Roll dough into a log; cut into 24 pieces. Roll each into a thin circle.',
      'Place 1 tsp filling in the centre, fold and pleat the edges to seal.',
      'Steam in a bamboo steamer over boiling water for 12–14 min.',
      'Serve immediately with dipping sauce of soy, vinegar and chili oil.',
    ],
  },
  {
    title: 'Street Tacos al Pastor',
    cuisine: 'Mexican',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80',
    timeMinutes: 35,
    difficulty: 'Medium',
    servings: 4,
    description:
      'Marinated pork seasoned with dried chillies, achiote and pineapple, seared until crispy and served in warm corn tortillas with fresh salsa.',
    keywords: ['pork', 'taco', 'pineapple', 'chili', 'corn', 'mexican'],
    dietTags: ['gluten-free'],
    ingredients: [
      { name: 'pork', quantity: 600, unit: 'g', raw: '600g pork shoulder, thinly sliced' },
      { name: 'pineapple', quantity: 0.5, unit: 'whole', raw: '½ pineapple, sliced' },
      { name: 'onion', quantity: 1, unit: 'whole', raw: '1 onion, diced' },
      { name: 'garlic', quantity: 2, unit: 'whole', raw: '2 garlic cloves' },
    ],
    steps: [
      'Blend soaked chillies, achiote, garlic, cumin and oregano with a splash of water.',
      'Marinate pork slices in this paste for at least 2 hours (overnight is best).',
      'Sear pork in a hot pan until caramelised and cooked through.',
      'Grill pineapple slices until lightly charred; dice.',
      'Warm corn tortillas on a dry griddle.',
      'Assemble tacos: pork, pineapple, diced onion, coriander and a squeeze of lime.',
    ],
  },
  {
    title: 'Tonkotsu Ramen',
    cuisine: 'Japanese',
    image: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80',
    timeMinutes: 180,
    difficulty: 'Hard',
    servings: 2,
    description:
      "A soul-warming bowl of rich, cloudy pork-bone broth simmered for hours, topped with chashu belly, soft-boiled marinated egg, bamboo shoots and nori.",
    keywords: ['pork', 'noodle', 'ramen', 'egg', 'broth', 'japanese', 'soup'],
    dietTags: [],
    ingredients: [
      { name: 'pork', quantity: 1, unit: 'kg', raw: '1 kg pork trotters & neck bones' },
      { name: 'noodle', quantity: 2, unit: 'whole', raw: '2 packs fresh ramen noodles' },
      { name: 'egg', quantity: 4, unit: 'whole', raw: '4 soft-boiled eggs, marinated in soy' },
      { name: 'soy', quantity: 3, unit: 'tbsp', raw: 'soy sauce, mirin' },
    ],
    steps: [
      'Blanch bones, rinse thoroughly, then simmer in fresh water 10–12 hrs.',
      'Strain broth; season with miso, soy and mirin.',
      'Roll pork belly tightly, tie with string and braise in soy, mirin and sake 2 hrs.',
      'Marinate soft-boiled eggs in soy, mirin and water overnight.',
      'Cook ramen noodles separately until al dente; drain.',
      'Assemble bowls: ladle broth, add noodles, top with all garnishes.',
    ],
  },
  {
    title: 'Salmon Nigiri Sushi',
    cuisine: 'Japanese',
    image: 'https://images.unsplash.com/photo-1559410545-0bdcd187e0a6?w=600&q=80',
    timeMinutes: 40,
    difficulty: 'Medium',
    servings: 2,
    description:
      'Perfectly seasoned sushi rice shaped by hand and topped with silky, buttery slices of sashimi-grade salmon. Simple elegance on a plate.',
    keywords: ['salmon', 'rice', 'fish', 'sushi', 'sashimi', 'seafood'],
    dietTags: ['gluten-free'],
    ingredients: [
      { name: 'rice', quantity: 2, unit: 'cup', raw: '2 cups Japanese short-grain rice' },
      { name: 'fish', quantity: 300, unit: 'g', raw: '300g sashimi-grade salmon, sliced' },
      { name: 'sugar', quantity: 1, unit: 'tbsp', raw: '1 tbsp sugar' },
    ],
    steps: [
      'Rinse rice until water runs clear; cook in rice cooker or pot.',
      'Mix rice vinegar, sugar and salt; fold into hot rice. Fan to cool.',
      'Wet hands with water; shape rice into oblongs (~30g each).',
      'Dab a tiny amount of wasabi on each rice ball.',
      'Drape a salmon slice over each rice ball; gently press to adhere.',
      'Serve with soy sauce and pickled ginger.',
    ],
  },
  {
    title: 'Ratatouille Provençale',
    cuisine: 'French',
    image: 'https://images.unsplash.com/photo-1543353071-087092ec393a?w=600&q=80',
    timeMinutes: 55,
    difficulty: 'Easy',
    servings: 4,
    description:
      'A sun-drenched Provençal stew of courgette, aubergine, tomatoes and peppers slowly braised with olive oil and herbes de Provence.',
    keywords: ['vegetable', 'tomato', 'courgette', 'aubergine', 'vegan', 'french', 'stew'],
    dietTags: ['vegan', 'vegetarian', 'gluten-free'],
    ingredients: [
      { name: 'tomato', quantity: 4, unit: 'whole', raw: '4 ripe tomatoes, chopped' },
      { name: 'onion', quantity: 1, unit: 'whole', raw: '1 onion' },
      { name: 'garlic', quantity: 4, unit: 'whole', raw: '4 garlic cloves' },
      { name: 'oil', quantity: 3, unit: 'tbsp', raw: '3 tbsp olive oil' },
    ],
    steps: [
      'Sauté onion in olive oil until soft; add garlic and cook 1 min.',
      'Add aubergine, cook 5 min until beginning to soften.',
      'Add peppers, courgettes and tomatoes. Season generously.',
      'Stir in herbes de Provence; cover and simmer 35–40 min.',
      'Uncover for the last 10 min to thicken the sauce.',
      'Finish with torn fresh basil and a glug of olive oil. Serve warm or at room temperature.',
    ],
  },
  {
    title: 'Green Curry Chicken',
    cuisine: 'Thai',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&q=80',
    timeMinutes: 40,
    difficulty: 'Medium',
    servings: 4,
    description:
      'A fragrant, fiery Thai curry balancing coconut milk, green chillies, lemongrass and Thai basil over tender chicken thigh.',
    keywords: ['chicken', 'coconut', 'curry', 'thai', 'chili', 'basil'],
    dietTags: ['gluten-free'],
    ingredients: [
      { name: 'chicken', quantity: 600, unit: 'g', raw: '600g chicken thigh, sliced' },
      { name: 'coconut', quantity: 400, unit: 'ml', raw: '400ml coconut milk' },
      { name: 'fish', quantity: 2, unit: 'tbsp', raw: '2 tbsp fish sauce' },
      { name: 'sugar', quantity: 1, unit: 'tbsp', raw: '1 tbsp palm sugar' },
    ],
    steps: [
      'Fry green curry paste in a splash of coconut cream until fragrant.',
      'Add chicken, stir to coat in the paste until seared.',
      'Pour in remaining coconut milk, fish sauce and palm sugar.',
      'Simmer 15–20 min until chicken is cooked through and sauce thickens.',
      'Add Thai basil and sliced chillies just before serving.',
      'Serve hot over jasmine rice.',
    ],
  },
  {
    title: 'Pad Thai',
    cuisine: 'Thai',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&q=80',
    timeMinutes: 30,
    difficulty: 'Medium',
    servings: 2,
    description:
      'Wok-tossed rice noodles in a tangy tamarind-lime sauce with shrimp, egg, bean sprouts and crushed peanuts.',
    keywords: ['noodle', 'shrimp', 'egg', 'peanut', 'thai', 'tamarind'],
    dietTags: [],
    ingredients: [
      { name: 'noodle', quantity: 200, unit: 'g', raw: '200g flat rice noodles' },
      { name: 'shrimp', quantity: 200, unit: 'g', raw: '200g shrimp, peeled' },
      { name: 'egg', quantity: 2, unit: 'whole', raw: '2 eggs' },
      { name: 'sugar', quantity: 2, unit: 'tbsp', raw: '2 tbsp palm sugar' },
    ],
    steps: [
      'Soak rice noodles in warm water until pliable; drain.',
      'Stir-fry shrimp in a hot wok until pink; push to one side.',
      'Scramble egg on the other side, then mix together.',
      'Add noodles and tamarind-fish sauce mixture; toss to coat.',
      'Fold in bean sprouts and garlic chives, toss briefly.',
      'Plate and top with crushed peanuts, lime wedge and chili flakes.',
    ],
  },
  {
    title: 'Bibimbap',
    cuisine: 'Korean',
    image: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=600&q=80',
    timeMinutes: 45,
    difficulty: 'Medium',
    servings: 2,
    description:
      'A vibrant bowl of warm rice topped with seasoned vegetables, marinated beef, a fried egg and a spoon of fiery gochujang.',
    keywords: ['rice', 'beef', 'egg', 'vegetable', 'korean', 'gochujang'],
    dietTags: ['gluten-free'],
    ingredients: [
      { name: 'rice', quantity: 2, unit: 'cup', raw: '2 cups cooked short-grain rice' },
      { name: 'beef', quantity: 250, unit: 'g', raw: '250g beef bulgogi-style strips' },
      { name: 'egg', quantity: 2, unit: 'whole', raw: '2 eggs, fried sunny-side up' },
      { name: 'carrot', quantity: 1, unit: 'whole', raw: '1 carrot, julienned' },
      { name: 'sesame', quantity: 1, unit: 'tbsp', raw: '1 tbsp sesame oil' },
    ],
    steps: [
      'Marinate beef strips in soy sauce, garlic and sesame oil for 20 min.',
      'Sear beef in a hot pan until caramelized; set aside.',
      'Blanch and season each vegetable separately (spinach, carrot, bean sprouts).',
      'Fry eggs sunny-side up, keeping yolks runny.',
      'Arrange rice in a bowl, fan vegetables and beef around the edge.',
      'Top with a fried egg and a generous spoon of gochujang; mix well before eating.',
    ],
  },
  {
    title: 'Kimchi Jjigae',
    cuisine: 'Korean',
    image: 'https://images.unsplash.com/photo-1580217593608-61931cefc821?w=600&q=80',
    timeMinutes: 30,
    difficulty: 'Easy',
    servings: 2,
    description:
      'A bubbling, deeply savory stew built on well-fermented kimchi, tofu and pork belly - Korea\'s ultimate cold-weather comfort food.',
    keywords: ['kimchi', 'tofu', 'pork', 'stew', 'korean', 'soup'],
    dietTags: ['gluten-free'],
    ingredients: [
      { name: 'tofu', quantity: 200, unit: 'g', raw: '200g firm tofu, cubed' },
      { name: 'pork', quantity: 150, unit: 'g', raw: '150g pork belly, sliced' },
      { name: 'onion', quantity: 1, unit: 'whole', raw: '1 onion, sliced' },
      { name: 'garlic', quantity: 2, unit: 'whole', raw: '2 garlic cloves' },
    ],
    steps: [
      'Render pork belly in a pot until lightly crisped.',
      'Add well-fermented kimchi and its juices; stir-fry 3–4 min.',
      'Pour in water or broth; bring to a boil.',
      'Simmer 15 min to deepen the flavor.',
      'Add tofu cubes and simmer 5 more minutes without stirring too much.',
      'Finish with sliced spring onion and serve bubbling hot with rice.',
    ],
  },
  {
    title: 'Goan Fish Curry',
    cuisine: 'Indian',
    image: 'https://images.unsplash.com/photo-1626777553635-be379dfe8e70?w=600&q=80',
    timeMinutes: 40,
    difficulty: 'Medium',
    servings: 4,
    description:
      'Firm white fish simmered in a tangy, coconut-milk curry built on toasted red chillies, tamarind and curry leaves - a coastal Goan classic.',
    keywords: ['fish', 'coconut', 'curry', 'tamarind', 'indian', 'seafood'],
    dietTags: ['gluten-free', 'dairy-free'],
    ingredients: [
      { name: 'fish', quantity: 600, unit: 'g', raw: '600g firm white fish (kingfish or pomfret), cut into steaks' },
      { name: 'coconut milk', quantity: 400, unit: 'ml', raw: '400ml coconut milk' },
      { name: 'tamarind', quantity: 1, unit: 'tbsp', raw: '1 tbsp tamarind pulp' },
      { name: 'dried red chili', quantity: 4, unit: 'whole', raw: '4 dried Kashmiri red chillies' },
      { name: 'coriander seed', quantity: 1, unit: 'tbsp', raw: '1 tbsp coriander seeds' },
      { name: 'turmeric', quantity: 1, unit: 'tsp', raw: '1 tsp turmeric' },
      { name: 'curry leaves', quantity: 10, unit: 'whole', raw: '10 curry leaves' },
      { name: 'onion', quantity: 1, unit: 'whole', raw: '1 onion, sliced' },
      { name: 'garlic', quantity: 4, unit: 'whole', raw: '4 garlic cloves' },
    ],
    steps: [
      'Toast dried chillies and coriander seeds, then grind with garlic into a paste.',
      'Sauté onion and curry leaves in oil until soft.',
      'Add the spice paste and turmeric; cook 2-3 minutes until fragrant.',
      'Pour in coconut milk and tamarind pulp; bring to a gentle simmer.',
      'Slide in fish steaks and poach 8-10 minutes, spooning sauce over top.',
      'Season with salt and serve hot with steamed rice.',
    ],
  },
  {
    title: 'Mutton Rogan Josh',
    cuisine: 'Indian',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&q=80',
    timeMinutes: 90,
    difficulty: 'Hard',
    servings: 4,
    description:
      'Slow-braised mutton in a rich, aromatic Kashmiri-red gravy of yogurt, fennel and Kashmiri chillies until fall-apart tender.',
    keywords: ['mutton', 'lamb', 'curry', 'kashmiri', 'indian', 'yogurt'],
    dietTags: ['gluten-free'],
    ingredients: [
      { name: 'mutton', quantity: 800, unit: 'g', raw: '800g mutton or lamb, bone-in, cut into chunks' },
      { name: 'yogurt', quantity: 200, unit: 'g', raw: '200g whisked yogurt' },
      { name: 'kashmiri chili powder', quantity: 3, unit: 'tbsp', raw: '3 tbsp Kashmiri chili powder' },
      { name: 'fennel seed', quantity: 2, unit: 'tsp', raw: '2 tsp ground fennel seeds' },
      { name: 'ginger', quantity: 1, unit: 'tbsp', raw: '1 tbsp ginger paste' },
      { name: 'garlic', quantity: 1, unit: 'tbsp', raw: '1 tbsp garlic paste' },
      { name: 'onion', quantity: 2, unit: 'whole', raw: '2 onions, sliced' },
      { name: 'ghee', quantity: 3, unit: 'tbsp', raw: '3 tbsp ghee' },
    ],
    steps: [
      'Brown mutton pieces in ghee in batches; set aside.',
      'Sauté onions until deep golden, then add ginger-garlic paste.',
      'Stir in Kashmiri chili powder and fennel; cook briefly to bloom the spices.',
      'Return mutton to the pot, add whisked yogurt a spoon at a time, stirring constantly.',
      'Add water to just cover, cover the pot and simmer 60-75 minutes until tender.',
      'Uncover and reduce to a thick gravy; finish with garam masala and serve with rice or naan.',
    ],
  },
  {
    title: 'Grilled Miso Salmon',
    cuisine: 'Japanese',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&q=80',
    timeMinutes: 25,
    difficulty: 'Easy',
    servings: 2,
    description:
      'Salmon fillets marinated in sweet miso, mirin and sake, then broiled until caramelized at the edges and silky within.',
    keywords: ['fish', 'salmon', 'miso', 'japanese', 'grilled'],
    dietTags: ['dairy-free'],
    ingredients: [
      { name: 'salmon', quantity: 2, unit: 'whole', raw: '2 salmon fillets' },
      { name: 'miso paste', quantity: 3, unit: 'tbsp', raw: '3 tbsp white miso paste' },
      { name: 'mirin', quantity: 2, unit: 'tbsp', raw: '2 tbsp mirin' },
      { name: 'sake', quantity: 2, unit: 'tbsp', raw: '2 tbsp sake' },
      { name: 'sugar', quantity: 1, unit: 'tbsp', raw: '1 tbsp sugar' },
    ],
    steps: [
      'Whisk miso, mirin, sake and sugar into a smooth marinade.',
      'Coat salmon fillets and marinate at least 30 minutes (overnight is best).',
      'Wipe off excess marinade and broil skin-side down 4-5 minutes.',
      'Flip and broil 3-4 more minutes until caramelized and cooked through.',
      'Serve with steamed rice and pickled ginger.',
    ],
  },
  {
    title: 'Peruvian Fish Ceviche',
    cuisine: 'Mexican',
    image: 'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?w=600&q=80',
    timeMinutes: 25,
    difficulty: 'Easy',
    servings: 4,
    description:
      'Fresh white fish "cooked" in lime juice with red onion, chili and cilantro - bright, briny and served ice-cold.',
    keywords: ['fish', 'lime', 'ceviche', 'seafood', 'fresh'],
    dietTags: ['gluten-free', 'dairy-free'],
    ingredients: [
      { name: 'fish', quantity: 500, unit: 'g', raw: '500g very fresh white fish (sea bass or snapper), diced' },
      { name: 'lime', quantity: 8, unit: 'whole', raw: '8 limes, juiced' },
      { name: 'red onion', quantity: 1, unit: 'whole', raw: '1 red onion, thinly sliced' },
      { name: 'chili', quantity: 1, unit: 'whole', raw: '1 aji or serrano chili, minced' },
      { name: 'cilantro', quantity: 0.25, unit: 'cup', raw: '¼ cup chopped cilantro' },
    ],
    steps: [
      'Toss diced fish with lime juice and a pinch of salt; refrigerate 15-20 minutes until opaque.',
      'Stir in red onion, chili and cilantro.',
      'Taste and adjust salt and lime.',
      'Serve immediately, ice-cold, with tostadas or plantain chips.',
    ],
  },
  {
    title: 'Lamb Kofta Curry',
    cuisine: 'Thai',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
    timeMinutes: 50,
    difficulty: 'Medium',
    servings: 4,
    description:
      'Spiced ground lamb meatballs simmered in a fragrant coconut-red curry sauce with Thai basil and chilies.',
    keywords: ['mutton', 'lamb', 'curry', 'coconut', 'thai', 'meatball'],
    dietTags: ['gluten-free', 'dairy-free'],
    ingredients: [
      { name: 'lamb', quantity: 500, unit: 'g', raw: '500g ground lamb (or mutton)' },
      { name: 'red curry paste', quantity: 3, unit: 'tbsp', raw: '3 tbsp Thai red curry paste' },
      { name: 'coconut milk', quantity: 400, unit: 'ml', raw: '400ml coconut milk' },
      { name: 'fish sauce', quantity: 1, unit: 'tbsp', raw: '1 tbsp fish sauce' },
      { name: 'basil', quantity: 0.5, unit: 'cup', raw: '½ cup Thai basil leaves' },
      { name: 'chili', quantity: 2, unit: 'whole', raw: '2 red chilies, sliced' },
    ],
    steps: [
      'Mix ground lamb with a little curry paste and salt; roll into small meatballs.',
      'Pan-sear meatballs until browned on all sides; set aside.',
      'Fry remaining curry paste in a splash of coconut cream until fragrant.',
      'Pour in the rest of the coconut milk and fish sauce; bring to a simmer.',
      'Return meatballs to the pan and simmer 12-15 minutes until cooked through.',
      'Stir in basil and chilies just before serving with jasmine rice.',
    ],
  },
];

module.exports = recipes;
